image: ubuntu:bionic
variables:
  DEBIAN_FRONTEND: noninteractive

test:
  script:
  - apt update
  - apt install -q -y python3-pip
  - apt build-dep -q -y ./
  - python3 -m pip install -U mypy==0.600
  - env python3 tests/testmanual_pep8.py
  - env MYPYPATH=$PWD/typehinting/ mypy ./apt
  - dpkg-buildpackage
  - make -C doc html
  artifacts:
    paths:
    - doc/build/html

pages:
  stage: deploy
  script:
  - mv doc/build/html/ public
  artifacts:
    paths:
    - public
  only:
  - master
